<a href="https://colab.research.google.com/github/AbhinavaReddy-hub/learning-DL-/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [ ]:
scaler=torch.tensor(3)
scaler

tensor(3)

In [ ]:
scaler.ndim

0

In [ ]:
scaler.shape

torch.Size([])

In [ ]:
vector=torch.tensor([1,2,3,4,5,6])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([6])

In [ ]:
MATRIX=torch.tensor([[1,2,3,4,5,6,],
                     [7,8,9,10,11,12]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 6])

In [ ]:
TENSOR=torch.tensor([[[1,2,3,4,5,6,],
                     [7,8,9,10,11,12]]])


In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 2, 6])

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.5650, 0.0360, 0.7348, 0.7110],
        [0.3334, 0.6907, 0.2688, 0.9362],
        [0.4600, 0.6753, 0.3873, 0.4323]])

In [ ]:
ZEROS=torch.zeros(3,3)
ZEROS

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ONES=torch.ones(3,3)
ONES

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
ONES.dtype

torch.float32

In [ ]:
a=torch.arange(10)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a=torch.arange(1,10,2)
a

tensor([1, 3, 5, 7, 9])

In [ ]:
a=torch.arange(4,18)
a

tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [ ]:
b=torch.zeros_like(a)
b

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float32_tensor

tensor([3., 6., 9.])

In [ ]:
float16_tensor=float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float32_tensor*float16_tensor

tensor([ 9., 36., 81.])

In [ ]:
print(float32_tensor.dtype)
print(float32_tensor.device)
print(float32_tensor.shape)

torch.float32
cpu
torch.Size([3])


In [ ]:
tensor=torch.rand(16).reshape(4,4)*10
tensor=tensor.type(torch.int32)
tensor

tensor([[1, 7, 7, 7],
        [5, 0, 6, 3],
        [4, 6, 2, 6],
        [0, 2, 5, 8]], dtype=torch.int32)

In [ ]:
print(tensor*tensor)

tensor([[ 1, 49, 49, 49],
        [25,  0, 36,  9],
        [16, 36,  4, 36],
        [ 0,  4, 25, 64]], dtype=torch.int32)


In [ ]:
print(torch.matmul(tensor,tensor))

tensor([[ 64,  63,  98, 126],
        [ 29,  77,  62,  95],
        [ 42,  52,  98, 106],
        [ 30,  46,  62, 100]], dtype=torch.int32)


In [ ]:
tensor@tensor

tensor([[ 64,  63,  98, 126],
        [ 29,  77,  62,  95],
        [ 42,  52,  98, 106],
        [ 30,  46,  62, 100]], dtype=torch.int32)

In [ ]:
torch.mm(tensor,tensor)

tensor([[ 64,  63,  98, 126],
        [ 29,  77,  62,  95],
        [ 42,  52,  98, 106],
        [ 30,  46,  62, 100]], dtype=torch.int32)

In [ ]:
tensor.max()

tensor(8, dtype=torch.int32)

In [ ]:
tensor.argmax()

tensor(15)

In [ ]:
x=torch.arange(1,10)
x.dtype

torch.int64

In [ ]:
x_stack=torch.stack([torch.zeros_like(x),x,x,x,torch.zeros_like(x)],dim=1)
x_stack,x

(tensor([[0, 1, 1, 1, 0],
         [0, 2, 2, 2, 0],
         [0, 3, 3, 3, 0],
         [0, 4, 4, 4, 0],
         [0, 5, 5, 5, 0],
         [0, 6, 6, 6, 0],
         [0, 7, 7, 7, 0],
         [0, 8, 8, 8, 0],
         [0, 9, 9, 9, 0]]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
tensor=torch.rand(3,1,2,1,4)
tensor,tensor.shape

(tensor([[[[[0.5407, 0.0467, 0.4663, 0.0806]],
 
           [[0.6251, 0.9482, 0.8743, 0.4152]]]],
 
 
 
         [[[[0.0847, 0.4324, 0.8931, 0.0145]],
 
           [[0.3586, 0.2297, 0.1459, 0.2872]]]],
 
 
 
         [[[[0.9060, 0.4914, 0.8052, 0.5447]],
 
           [[0.9203, 0.2329, 0.4693, 0.7502]]]]]),
 torch.Size([3, 1, 2, 1, 4]))

In [ ]:
tensor.squeeze(),tensor.squeeze().shape

(tensor([[[0.5407, 0.0467, 0.4663, 0.0806],
          [0.6251, 0.9482, 0.8743, 0.4152]],
 
         [[0.0847, 0.4324, 0.8931, 0.0145],
          [0.3586, 0.2297, 0.1459, 0.2872]],
 
         [[0.9060, 0.4914, 0.8052, 0.5447],
          [0.9203, 0.2329, 0.4693, 0.7502]]]),
 torch.Size([3, 2, 4]))

In [ ]:
tensor.unsqueeze(dim=2),tensor.unsqueeze(dim=2
                                         ).shape

(tensor([[[[[[0.5407, 0.0467, 0.4663, 0.0806]],
 
            [[0.6251, 0.9482, 0.8743, 0.4152]]]]],
 
 
 
 
         [[[[[0.0847, 0.4324, 0.8931, 0.0145]],
 
            [[0.3586, 0.2297, 0.1459, 0.2872]]]]],
 
 
 
 
         [[[[[0.9060, 0.4914, 0.8052, 0.5447]],
 
            [[0.9203, 0.2329, 0.4693, 0.7502]]]]]]),
 torch.Size([3, 1, 1, 2, 1, 4]))

In [ ]:
x_permute=torch.rand(224,224,3)
print(x_permute.shape)
x_permute=x_permute.permute(2,0,1)
print(x_permute.shape)
x_permute

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


tensor([[[0.3204, 0.7730, 0.0592,  ..., 0.4746, 0.5585, 0.8245],
         [0.1708, 0.8229, 0.1700,  ..., 0.8821, 0.0848, 0.1823],
         [0.4890, 0.0098, 0.1958,  ..., 0.8188, 0.7706, 0.0725],
         ...,
         [0.4046, 0.9104, 0.4757,  ..., 0.9974, 0.0890, 0.8910],
         [0.7927, 0.0198, 0.1044,  ..., 0.0924, 0.9305, 0.0498],
         [0.5748, 0.5309, 0.0310,  ..., 0.7614, 0.3140, 0.7982]],

        [[0.9098, 0.7499, 0.2034,  ..., 0.6923, 0.0061, 0.8089],
         [0.8461, 0.0568, 0.1570,  ..., 0.1220, 0.6585, 0.7913],
         [0.3846, 0.0453, 0.0305,  ..., 0.5681, 0.9131, 0.8339],
         ...,
         [0.4904, 0.6328, 0.2000,  ..., 0.1246, 0.9589, 0.3804],
         [0.1434, 0.2129, 0.3057,  ..., 0.7801, 0.2191, 0.8737],
         [0.8366, 0.0339, 0.2204,  ..., 0.1284, 0.3823, 0.1313]],

        [[0.4846, 0.0443, 0.8676,  ..., 0.9932, 0.2465, 0.0946],
         [0.4739, 0.3304, 0.5070,  ..., 0.2327, 0.4451, 0.4953],
         [0.3868, 0.1509, 0.8907,  ..., 0.0598, 0.3212, 0.