In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

In [3]:
iris=datasets.load_iris()
X=iris.data
y=iris.target
print(X.shape,X)
print(y.shape,y)

(150, 4) [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6

In [8]:
# Normalize the features
scaler=StandardScaler()
X=scaler.fit_transform(X)
print(X.shape,X)
#here we do not apply standard scaler for the y because we train the model only by using X data

(150, 4) [[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.

In [9]:
# Convert data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)


In [10]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [30]:
class IrisNN (nn.Module):
    def __init__(self):
        super(IrisNN,self).__init__()
        self.fc1=nn.Linear(4,64)
        # self.fc3=nn.Linear(5,5)
        self.fc2=nn.Linear(64,3)
        self.relu=nn.ReLU()
    def forward(self,x):
        x=self.fc1(x)
        x=self.relu(x)
        x=self.fc2(x)
        return x
        

In [31]:
model=IrisNN()
criterion=nn.CrossEntropyLoss()
optimizer=optim.SGD(model.parameters(),lr=0.01)


In [32]:
epochs=1000
for epoch in range(epochs):
    model.train()
    optimizer.zero_grad()
    predictions=model(X_train)
    loss=criterion(predictions,y_train)
    loss.backward()
    optimizer.step()
    if epoch%100==0:
        print(f"{epoch} , loss:{loss}")


0 , loss:1.0075241327285767
100 , loss:0.521531343460083
200 , loss:0.4174371063709259
300 , loss:0.36295536160469055
400 , loss:0.32557597756385803
500 , loss:0.2963391840457916
600 , loss:0.2715626657009125
700 , loss:0.24986021220684052
800 , loss:0.23063628375530243
900 , loss:0.21364916861057281


In [33]:
model.eval()
with torch.no_grad():
    test_outputs=model(X_test)
    print(test_outputs)
    print(torch.max(test_outputs,1))
    _, predicted_classes = torch.max(test_outputs, 1)  # Get the class with the highest score
    accuracy = (predicted_classes == y_test).sum().item() / y_test.size(0)
    print(f"Accuracy: {accuracy * 100}%")

tensor([[-1.7991e+00,  2.1270e+00,  7.6119e-01],
        [ 3.6203e+00, -2.3575e-01, -2.5187e+00],
        [-5.6650e+00,  2.2932e+00,  6.4612e+00],
        [-1.8409e+00,  1.7855e+00,  1.1712e+00],
        [-2.7367e+00,  2.2313e+00,  1.8564e+00],
        [ 3.3224e+00,  1.6365e-02, -2.6121e+00],
        [-4.0374e-01,  1.5355e+00, -4.7327e-01],
        [-3.3064e+00,  1.4223e+00,  3.7780e+00],
        [-3.1116e+00,  2.8316e+00,  2.0178e+00],
        [-1.2276e+00,  2.0645e+00,  6.5982e-05],
        [-2.5578e+00,  1.3124e+00,  2.7828e+00],
        [ 3.6603e+00,  3.5653e-01, -3.1799e+00],
        [ 3.6790e+00, -4.3498e-02, -2.8054e+00],
        [ 3.6420e+00,  2.6217e-01, -3.0735e+00],
        [ 4.4317e+00, -6.6928e-01, -2.8507e+00],
        [-1.4424e+00,  1.3007e+00,  1.2163e+00],
        [-3.4602e+00,  1.4247e+00,  4.1016e+00],
        [-1.1896e+00,  2.3417e+00, -1.3493e-01],
        [-1.4759e+00,  1.9054e+00,  6.0530e-01],
        [-3.6670e+00,  1.6060e+00,  4.1788e+00],
        [ 3.9291e+00